"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type ChartConfig = { symbol: string; interval: string; label: string };
type Tool = "trend" | "horizontal" | "rectangle" | "fib" | null;
type Point = { x: number; y: number };
type Drawing = { type: Exclude<Tool, null>; a: Point; b: Point };
type Candle = { o:number; h:number; l:number; c:number };

const symbols = [
 {symbol:"BTCUSD",name:"Bitcoin / TetherUS",price:"79,146.01",change:"+1,412.01",percent:"+1.82%",positive:true,icon:"₿"},
 {symbol:"SOLUSD",name:"SOL / TetherUS",price:"96.05",change:"+0.62",percent:"+0.65%",positive:true,icon:"S"},
 {symbol:"XAUUSD",name:"Gold Spot / U.S. Dollar",price:"4,654.08",change:"+51.095",percent:"+1.11%",positive:true,icon:"Au"},
 {symbol:"ETHUSD",name:"Ethereum / TetherUS",price:"2,480.28",change:"+16.87",percent:"+0.68%",positive:true,icon:"◆"},
 {symbol:"USDCHF",name:"U.S. Dollar / Swiss Franc",price:"0.8023",change:"+0.00099",percent:"+0.12%",positive:true,icon:"$"},
 {symbol:"EURUSD",name:"Euro / U.S. Dollar",price:"1.1663",change:"−0.00135",percent:"−0.12%",positive:false,icon:"€"},
 {symbol:"AUDUSD",name:"Australian Dollar / U.S. Dollar",price:"0.7149",change:"−0.00210",percent:"−0.29%",positive:false,icon:"A$"}
];
const intervals=[{interval:"1",label:"1m"},{interval:"5",label:"5m"},{interval:"15",label:"15m"},{interval:"60",label:"1H"},{interval:"240",label:"4H"},{interval:"D",label:"1D"}];
const defaultCharts:ChartConfig[]=[{symbol:"XAUUSD",interval:"5",label:"5m"},{symbol:"XAUUSD",interval:"15",label:"15m"},{symbol:"XAUUSD",interval:"60",label:"1H"},{symbol:"XAUUSD",interval:"240",label:"4H"}];

function makeCandles(symbol:string, count=150):Candle[]{
 let seed=Array.from(symbol).reduce((a,c)=>a+c.charCodeAt(0),0); let price=symbol.includes("XAU")?4650:symbol.includes("BTC")?79000:symbol.includes("ETH")?2480:symbol.includes("SOL")?96:1.16;
 const out:Candle[]=[]; const rnd=()=>{seed=(seed*9301+49297)%233280;return seed/233280};
 for(let i=0;i<count;i++){const o=price;const move=(rnd()-.47)*(price*.012);const c=Math.max(.0001,o+move);const h=Math.max(o,c)*(1+rnd()*.004);const l=Math.min(o,c)*(1-rnd()*.004);out.push({o,h,l,c});price=c} return out;
}

function CandleChart({symbol,interval}:{symbol:string;interval:string}){
 const ref=useRef<HTMLCanvasElement|null>(null); const [zoom,setZoom]=useState(1); const [offset,setOffset]=useState(0); const drag=useRef<{x:number;offset:number}|null>(null); const candles=useMemo(()=>makeCandles(symbol),[symbol]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const parent=canvas.parentElement;if(!parent)return;const draw=()=>{const dpr=window.devicePixelRatio||1,w=parent.clientWidth,h=parent.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";const x=canvas.getContext("2d");if(!x)return;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle="#fff";x.fillRect(0,0,w,h);const left=10,right=62,top=12,bottom=28,cw=w-left-right,ch=h-top-bottom;const count=Math.max(35,Math.min(150,Math.floor(70*zoom)));const start=Math.max(0,Math.min(candles.length-count+1,Math.floor(offset)));const visible=candles.slice(start,start+count);const hi=Math.max(...visible.map(v=>v.h)),lo=Math.min(...visible.map(v=>v.l));const py=(v:number)=>top+(hi-v)/(hi-lo||1)*ch;const gap=cw/visible.length;const body=Math.max(2,gap*.62);
 x.strokeStyle="#eceef1";x.lineWidth=1;for(let i=0;i<=6;i++){const y=top+ch*i/6;x.beginPath();x.moveTo(left,y);x.lineTo(left+cw,y);x.stroke()}for(let i=0;i<=8;i++){const xx=left+cw*i/8;x.beginPath();x.moveTo(xx,top);x.lineTo(xx,top+ch);x.stroke()}
 visible.forEach((v,i)=>{const xx=left+i*gap+gap/2,yo=py(v.o),yc=py(v.c),yh=py(v.h),yl=py(v.l),up=v.c>=v.o;x.strokeStyle=up?"#16a085":"#e04b5f";x.fillStyle=x.strokeStyle;x.lineWidth=1; x.beginPath();x.moveTo(xx,yh);x.lineTo(xx,yl);x.stroke();const bh=Math.max(1,Math.abs(yc-yo));x.fillRect(xx-body/2,Math.min(yo,yc),body,bh)});
 x.fillStyle="#667085";x.font="12px Inter, sans-serif";for(let i=0;i<=6;i++){const v=hi-(hi-lo)*i/6;x.fillText(v.toFixed(symbol.includes("XAU")?2: symbol.includes("BTC")?0:4),left+cw+7,top+ch*i/6+4)}x.fillStyle="#667085";x.fillText(`${symbol} · ${intervals.find(q=>q.interval===interval)?.label||interval}`,12,h-8);};draw();const ro=new ResizeObserver(draw);ro.observe(parent);return()=>ro.disconnect()},[candles,zoom,offset,symbol,interval]);
 const down=(e:React.PointerEvent)=>{drag.current={x:e.clientX,offset};e.currentTarget.setPointerCapture(e.pointerId)};const move=(e:React.PointerEvent)=>{if(!drag.current)return;const dx=e.clientX-drag.current.x;setOffset(Math.max(0,drag.current.offset-dx/8))};const up=()=>{drag.current=null};
 return <canvas ref={ref} className="candle-canvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>{e.preventDefault();setZoom(z=>Math.max(.55,Math.min(3,z+(e.deltaY<0?.12:-.12))))}}/>;
}

function DrawingOverlay({tool,drawings,onAdd}:{tool:Tool;drawings:Drawing[];onAdd:(d:Drawing)=>void}){const [start,setStart]=useState<Point|null>(null);const point=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const down=(e:React.PointerEvent<SVGSVGElement>)=>{if(!tool)return;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);if(tool==="horizontal"){onAdd({type:tool,a:p,b:{x:e.currentTarget.clientWidth,y:p.y}});return}setStart(p)};const up=(e:React.PointerEvent<SVGSVGElement>)=>{if(!tool||!start||tool==="horizontal")return;onAdd({type:tool,a:start,b:point(e)});setStart(null)};return <svg className={`drawing-overlay ${tool?"drawing-active":""}`} onPointerDown={down} onPointerUp={up}>{drawings.map((d,i)=>d.type==="horizontal"?<line key={i} x1="0" y1={d.a.y} x2="100%" y2={d.a.y} className="drawing-line"/>:d.type==="rectangle"?<rect key={i} x={Math.min(d.a.x,d.b.x)} y={Math.min(d.a.y,d.b.y)} width={Math.abs(d.b.x-d.a.x)} height={Math.abs(d.b.y-d.a.y)} className="drawing-rect"/>:<line key={i} x1={d.a.x} y1={d.a.y} x2={d.b.x} y2={d.b.y} className="drawing-line"/>)}</svg>}

export default function Home(){
 const [page,setPage]=useState<"watchlist"|"chart">("watchlist");const [charts,setCharts]=useState<ChartConfig[]>(defaultCharts);const [layout,setLayout]=useState(1);const [toolsOpen,setToolsOpen]=useState(false);const [layoutOpen,setLayoutOpen]=useState(false);const [tool,setTool]=useState<Tool>(null);const [drawings,setDrawings]=useState<Record<number,Drawing[]>>({});const [restored,setRestored]=useState(false);const visibleCharts=useMemo(()=>charts.slice(0,layout),[charts,layout]);
 useEffect(()=>{try{const p=localStorage.getItem("tradingwig-page") as "watchlist"|"chart"|null;const c=localStorage.getItem("tradingwig-charts");const l=localStorage.getItem("tradingwig-layout");if(p)setPage(p);if(c)setCharts(JSON.parse(c));if(l)setLayout(Math.max(1,Math.min(4,Number(l)||1)))}catch{}setRestored(true)},[]);useEffect(()=>{if(restored)localStorage.setItem("tradingwig-page",page)},[page,restored]);useEffect(()=>{if(restored)localStorage.setItem("tradingwig-charts",JSON.stringify(charts))},[charts,restored]);useEffect(()=>{if(restored)localStorage.setItem("tradingwig-layout",String(layout))},[layout,restored]);
 const openSymbol=(symbol:string)=>{setCharts(c=>c.map((x,i)=>i===0?{...x,symbol}:x));setLayout(1);setPage("chart")};const setInterval=(i:number,interval:string,label:string)=>setCharts(c=>c.map((x,j)=>j===i?{...x,interval,label}:x));
 if(page==="watchlist")return <main className="mobile-app watchlist-page"><header className="watchlist-header"><button className="icon-button">•••</button><div className="tv-logo">T7</div><button className="icon-button search-icon">⌕</button></header><div className="watchlist-tabs"><button className="hamburger">☰</button><button className="list-tab active">Watchlist</button><button className="add-list">＋ Add list</button></div><section className="quotes">{symbols.map(item=><button className="quote-row" key={item.symbol} onClick={()=>openSymbol(item.symbol)}><span className={`asset-icon ${item.symbol}`}>{item.icon}</span><span className="quote-main"><strong>{item.symbol}</strong><small>{item.name}</small></span><span className="quote-values"><strong>{item.price}</strong><small className={item.positive?"up":"down"}>{item.change} {item.percent}</small></span></button>)}</section><button className="add-symbol">＋ Add Symbol</button><nav className="bottom-nav"><button className="nav-item active"><span>▤</span><b>Watchlist</b></button><button className="nav-item" onClick={()=>setPage("chart")}><span>⌁</span><b>Chart</b></button><button className="nav-item"><span>◈</span><b>Explore</b></button><button className="nav-item"><span>♧</span><b>Community</b></button><button className="nav-item"><span>☰</span><b>Menu</b></button></nav></main>;
 return <main className="mobile-app chart-page"><section className={`chart-stage layout-${layout}`}>{visibleCharts.map((chart,index)=><article className="chart-card" key={index}><CandleChart symbol={chart.symbol} interval={chart.interval}/><DrawingOverlay tool={index===0?tool:null} drawings={drawings[index]||[]} onAdd={d=>setDrawings(v=>({...v,[index]:[...(v[index]||[]),d]}))}/></article>)}</section><section className="chart-controls"><div className="tool-row"><button className={`tool-button ${toolsOpen||tool?"active":""}`} onClick={()=>{setToolsOpen(!toolsOpen);setLayoutOpen(false)}}>✎</button><button className="tool-button">⌁</button><button className="tool-button more" onClick={()=>setTool(null)}>•••</button><button className="tool-button" onClick={()=>setDrawings({})}>↶</button></div>{toolsOpen&&<div className="tools-menu"><button onClick={()=>{setTool("trend");setToolsOpen(false)}}>Trend Line</button><button onClick={()=>{setTool("horizontal");setToolsOpen(false)}}>Horizontal Line</button><button onClick={()=>{setTool("rectangle");setToolsOpen(false)}}>Rectangle</button></div>}<div className="layout-row"><button className={`layout-button ${layoutOpen?"active":""}`} onClick={()=>{setLayoutOpen(!layoutOpen);setToolsOpen(false)}}>▦ <span>Layout</span></button></div>{layoutOpen&&<div className="layout-menu">{[1,2,4].map(n=><button key={n} className={layout===n?"selected":""} onClick={()=>{setLayout(n);setLayoutOpen(false)}}>{n} Charts</button>)}</div>}</section><nav className="bottom-nav"><button className="nav-item" onClick={()=>setPage("watchlist")}><span>▤</span><b>Watchlist</b></button><button className="nav-item active"><span>⌁</span><b>Chart</b></button><button className="nav-item"><span>◈</span><b>Explore</b></button><button className="nav-item"><span>♧</span><b>Community</b></button><button className="nav-item"><span>☰</span><b>Menu</b></button></nav></main>;
}
